version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: elsms_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: elsms_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - elsms_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: elsms_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@elsms.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - elsms_network

volumes:
  pgdata:
    driver: local

networks:
  elsms_network:
    driver: bridge
