-- Add missing columns to zones table for seat editor
ALTER TABLE zones 
ADD COLUMN IF NOT EXISTS color TEXT DEFAULT '#10B981',
ADD COLUMN IF NOT EXISTS grid_block_size DECIMAL DEFAULT 0.5,
ADD COLUMN IF NOT EXISTS seat_size DECIMAL DEFAULT 1.0,
ADD COLUMN IF NOT EXISTS canvas_width DECIMAL DEFAULT 20,
ADD COLUMN IF NOT EXISTS canvas_height DECIMAL DEFAULT 15,
ADD COLUMN IF NOT EXISTS features TEXT[] DEFAULT '{}';
